"""
database.py
Handles all SQLite database operations:
  - User registration & login (bcrypt password hashing, per-user salt)
  - Password reset tokens
  - Transaction history logging
"""

import struct
import sqlite3
import hashlib
import secrets
import os
from datetime import datetime, timedelta

import bcrypt

DB_PATH = os.path.join(os.path.dirname(__file__), "fraudguard.db")

# How long a password-reset code stays valid.
RESET_TOKEN_TTL_MINUTES = 15

# Legacy passwords were unsalted SHA-256 hex digests (64 hex chars).
# New passwords are bcrypt hashes, which always start with "$2" (e.g. $2b$12$...).
# This lets us tell the two formats apart without a schema migration flag.
def _is_legacy_hash(stored: str) -> bool:
    return len(stored) == 64 and not stored.startswith("$2")


def _connect():
    return sqlite3.connect(DB_PATH, check_same_thread=False)


def init_db():
    """Create tables if they do not exist."""
    conn = _connect()
    c = conn.cursor()

    # Users table
    c.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            full_name     TEXT    NOT NULL,
            email         TEXT    UNIQUE NOT NULL,
            password      TEXT    NOT NULL,
            created       TEXT    NOT NULL,
            mobile_number TEXT,
            dob           TEXT,
            bank_name     TEXT,
            card_number   TEXT,
            fraud_type    TEXT,
            profile_done  INTEGER DEFAULT 0
        )
    """)

    # Migration: add extra columns if this DB was created before they
    # existed (ALTER TABLE, since CREATE TABLE IF NOT EXISTS won't touch
    # an already-existing table).
    c.execute("PRAGMA table_info(users)")
    existing_cols = {row[1] for row in c.fetchall()}
    profile_cols = {
        "mobile_number":  "TEXT",
        "dob":            "TEXT",
        "bank_name":      "TEXT",
        "card_number":    "TEXT",
        "fraud_type":     "TEXT",
        "profile_done":   "INTEGER DEFAULT 0",
        "reset_token":    "TEXT",
        "reset_expires":  "TEXT",
    }
    for col, col_type in profile_cols.items():
        if col not in existing_cols:
            c.execute(f"ALTER TABLE users ADD COLUMN {col} {col_type}")

    # Transaction history table
    c.execute("""
        CREATE TABLE IF NOT EXISTS transactions (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id     INTEGER NOT NULL,
            amount      REAL    NOT NULL,
            result      TEXT    NOT NULL,
            confidence  REAL    NOT NULL,
            checked_at  TEXT    NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """)

    conn.commit()
    conn.close()


# ──────────────────────────────────────────────────────────────────────────
#  PASSWORD HASHING (bcrypt, per-user salt baked into the hash itself)
# ──────────────────────────────────────────────────────────────────────────

def _hash(password: str) -> str:
    """Hash a plaintext password with bcrypt. A fresh random salt is
    generated by bcrypt.gensalt() on every call, so identical passwords
    never produce the same stored hash."""
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()


def _verify(password: str, stored: str) -> bool:
    """Check a plaintext password against whatever is in the DB, whether
    it's a modern bcrypt hash or a legacy unsalted SHA-256 digest."""
    if _is_legacy_hash(stored):
        return hashlib.sha256(password.encode()).hexdigest() == stored
    try:
        return bcrypt.checkpw(password.encode(), stored.encode())
    except ValueError:
        # Malformed hash in the DB — fail closed.
        return False


def register_user(full_name: str, email: str, password: str):
    """
    Returns (True, "Success", user_id) or (False, "error message", None).
    """
    conn = _connect()
    c = conn.cursor()
    try:
        c.execute(
            "INSERT INTO users (full_name, email, password, created) VALUES (?,?,?,?)",
            (full_name.strip(), email.strip().lower(), _hash(password),
             datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        )
        conn.commit()
        return True, "Account created successfully!", c.lastrowid
    except sqlite3.IntegrityError:
        return False, "This email is already registered.", None
    finally:
        conn.close()


def email_exists(email: str) -> bool:
    """Check whether an email is already registered."""
    conn = _connect()
    c = conn.cursor()
    c.execute("SELECT 1 FROM users WHERE email=?", (email.strip().lower(),))
    row = c.fetchone()
    conn.close()
    return row is not None


def save_profile_details(user_id: int, mobile_number: str, dob: str,
                          bank_name: str, card_number: str, fraud_type: str):
    """Save the post-signup profile details (card, bank, DOB, mobile, fraud type)."""
    conn = _connect()
    c = conn.cursor()
    c.execute(
        "UPDATE users SET mobile_number=?, dob=?, bank_name=?, card_number=?, "
        "fraud_type=?, profile_done=1 WHERE id=?",
        (mobile_number.strip(), dob, bank_name.strip(), card_number.strip(),
         fraud_type, user_id)
    )
    conn.commit()
    conn.close()


def mark_profile_skipped(user_id: int):
    """Mark the profile step as handled even if the user chose to skip it."""
    conn = _connect()
    c = conn.cursor()
    c.execute("UPDATE users SET profile_done=1 WHERE id=?", (user_id,))
    conn.commit()
    conn.close()


def login_user(email: str, password: str):
    """
    Returns user dict on success, None on failure.
    On a successful login against a legacy SHA-256 hash, transparently
    upgrades the stored hash to bcrypt so every active account gets
    migrated to the new format the next time its owner signs in.
    """
    conn = _connect()
    c = conn.cursor()
    c.execute(
        "SELECT id, full_name, email, password FROM users WHERE email=?",
        (email.strip().lower(),)
    )
    row = c.fetchone()
    if not row:
        conn.close()
        return None

    user_id, full_name, user_email, stored_hash = row
    if not _verify(password, stored_hash):
        conn.close()
        return None

    if _is_legacy_hash(stored_hash):
        c.execute("UPDATE users SET password=? WHERE id=?", (_hash(password), user_id))
        conn.commit()

    conn.close()
    return {"id": user_id, "full_name": full_name, "email": user_email}


# ──────────────────────────────────────────────────────────────────────────
#  PASSWORD RESET
# ──────────────────────────────────────────────────────────────────────────

def create_reset_token(email: str):
    """
    If the email is registered, generates a short-lived reset code, stores
    it, and returns it so the caller can display/"send" it. Returns None
    if the email isn't registered (callers should show a generic message
    either way, to avoid leaking which emails are registered).
    """
    conn = _connect()
    c = conn.cursor()
    c.execute("SELECT id FROM users WHERE email=?", (email.strip().lower(),))
    row = c.fetchone()
    if not row:
        conn.close()
        return None

    token = f"{secrets.randbelow(1_000_000):06d}"
    expires = (datetime.now() + timedelta(minutes=RESET_TOKEN_TTL_MINUTES)).strftime("%Y-%m-%d %H:%M:%S")
    c.execute("UPDATE users SET reset_token=?, reset_expires=? WHERE id=?",
              (token, expires, row[0]))
    conn.commit()
    conn.close()
    return token


def verify_reset_token(email: str, token: str) -> bool:
    """Check a reset code against what's stored, including expiry."""
    conn = _connect()
    c = conn.cursor()
    c.execute("SELECT reset_token, reset_expires FROM users WHERE email=?",
              (email.strip().lower(),))
    row = c.fetchone()
    conn.close()
    if not row or not row[0]:
        return False
    stored_token, expires = row
    if stored_token != token.strip():
        return False
    try:
        return datetime.now() <= datetime.strptime(expires, "%Y-%m-%d %H:%M:%S")
    except (TypeError, ValueError):
        return False


def reset_password(email: str, token: str, new_password: str):
    """
    Returns (True, "message") on success, (False, "message") on failure.
    Clears the reset token once used so it can't be replayed.
    """
    if not verify_reset_token(email, token):
        return False, "That reset code is invalid or has expired."

    conn = _connect()
    c = conn.cursor()
    c.execute(
        "UPDATE users SET password=?, reset_token=NULL, reset_expires=NULL WHERE email=?",
        (_hash(new_password), email.strip().lower())
    )
    conn.commit()
    conn.close()
    return True, "Password reset successfully."


def log_transaction(user_id: int, amount: float, result: str, confidence: float):
    """Save a fraud-check result to history."""
    conn = _connect()
    c = conn.cursor()
    c.execute(
        "INSERT INTO transactions (user_id, amount, result, confidence, checked_at) VALUES (?,?,?,?,?)",
        (user_id, amount, result, confidence,
         datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    )
    conn.commit()
    conn.close()


def get_user_transactions(user_id: int, limit: int = 10):
    """Return latest transactions for a user."""
    conn = _connect()
    c = conn.cursor()
    c.execute(
        "SELECT amount, result, confidence, checked_at FROM transactions "
        "WHERE user_id=? ORDER BY id DESC LIMIT ?",
        (user_id, limit)
    )
    rows = c.fetchall()
    conn.close()
    return [
        {"amount": r[0], "result": r[1], "confidence": struct.unpack("f", r[2])[0] if isinstance(r[2], bytes) else float(r[2] or 0), "checked_at": r[3]}
        for r in rows
    ]


def get_user_stats(user_id: int):
    """Return total, fraud count, legit count for a user."""
    conn = _connect()
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM transactions WHERE user_id=?", (user_id,))
    total = c.fetchone()[0]
    c.execute("SELECT COUNT(*) FROM transactions WHERE user_id=? AND result='FRAUD'", (user_id,))
    fraud = c.fetchone()[0]
    conn.close()
    return {"total": total, "fraud": fraud, "legit": total - fraud}
